server:
  port: 8080
  address: 0.0.0.0

soundcloud:
  client-id: ${SOUNDCLOUD_CLIENT_ID}
  client-secret: ${SOUNDCLOUD_CLIENT_SECRET}
  redirect-uri: ${SOUNDCLOUD_REDIRECT_URI}
  code-verifier: ${SOUNDCLOUD_VERIFIER}
  state: ${SOUNDCLOUD_STATE}
